apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubactions-aks-geopagos-configserver
spec:
  selector:
    matchLabels:
      app: githubactions-aks-geopagos-configserver
  template:
    metadata:
      labels:
        app: githubactions-aks-geopagos-configserver
    spec:
      containers:
      - name: githubactions-aks-geopagos-configserver
        image: agonzalesr93/configserver
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
