apiVersion: v1
kind: Service
metadata:
  name: githubactions-aks-geopagos-configserver-service
spec:
  selector:
    app: githubactions-aks-geopagos-configserver
    type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 80
